### ISSUE TITLE
AttributeError: module 'typing' has no attribute '_SpecialForm'

### ISSUE THREAD

**Issue by neverusedname** [abhinavsingh/proxy.py#231] opened 2019-12-17 07:12 UTC
I am using python 3.7 on windows, and I got this error.

```cmd
E:\Python37>python -m proxy
Traceback (most recent call last):
  File "E:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python37\lib\site-packages\proxy.py", line 45, in <module>
    from typing_extensions import Protocol
  File "E:\Python37\lib\site-packages\typing_extensions.py", line 361, in <modul
e>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
```

**Comment by abhinavsingh** [comment] 2019-12-17 15:39
Hi Liu,

Thanks for reporting this. Unsure what the root cause here might be. Unfortunately, I also don't have a windows machine to try this out.

Few things to check here:
1. How did you install `typing_extensions`?
2. Can you make sure it matches the version in requirements file e.g. `pip install -r requirements.txt`.  Lemme know if it helps

Thank you.

**Comment by neverusedname** [comment] 2019-12-18 05:45
Hi, abhinavsingh. thanks for your reply. 

I just pip installed proxy.py,  and typing_extensions got installed automatically. I checked the version of typings_extensions, and seemed like 3.7.4.0, I am not sure. And then I checked requirements.txt, it says typing-extensions==3.7.4.1, so I pip unintalled 3.7.4.0 and installed 3.7.4.1.  There seems no __SpecialForm in typing_extension module for windows. 

And BTW,  I originally used python 3.5.2, seems like python 3.5.2 cannot run proxy.py because python3.5.2 does not support certain new grammer, and error went like this:
```
Traceback (most recent call last):
  File "D:\Python35\lib\runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Python35\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\Python35\lib\site-packages\proxy.py", line 57
    DEFAULT_DISABLE_HEADERS: List[bytes] = []
                           ^
```
 So maybe proxy.py is tested on python3 only with versions greater than 3.5? 
Thanks :)

**Comment by abhinavsingh** [comment] 2019-12-18 05:56
Yep, only 3.5+.  Your logs suggested Python37 and hence I didn't pointed this out earlier :)

<img width="281" alt="Screen Shot 2019-12-17 at 9 56 54 PM" src="https://user-images.githubusercontent.com/126065/71059555-fe24a400-2117-11ea-8ace-42ab26a750fc.png">

Unfortunately, current `pip` release doesn't contain `require_python` guard and hence it gets installed even on unsupported version.  This should be fixed in the next release i.e. `v2.x`.  If you want to give it a try, see https://github.com/abhinavsingh/proxy.py#development-version-with-pip

**Comment by abhinavsingh** [comment] 2019-12-18 06:01
@neverusedname Python `typing` module was added in `3.5` https://docs.python.org/3/library/typing.html but unsure if it started supporting typed syntax from day 1 or in the later releases.

`proxy.py` is tested on `Python 3.5` and hence the badge :)  See GitHub actions https://github.com/abhinavsingh/proxy.py/runs/348921617 but I think GitHub actions too uses the latest 3.5.x version.

**Closed by abhinavsingh** 2019-12-18 06:01 UTC
Labels: Question

**Comment by 13096676951x** [comment] 2022-04-21 02:08
Hello, I have encountered this problem when I run the code, but my Python is version 3.6.11, can you tell me how you solve this problem? Very grateful for your help

**Comment by abhinavsingh** [comment] 2022-04-21 07:17
Can you try to install latest `typing-extension`.   We have GitHub workflow integration and e2e unit and integration tests.   They seem to work fine on `Python 3.6.x`.   Unsure if this is an issue related specifically to `3.6.11`.

I looked into our workflows, looks like GHA uses `3.6.15` , see https://github.com/abhinavsingh/proxy.py/runs/6099188780?check_suite_focus=true

Can you try the same version and check if u still get errors.

<img width="1005" alt="Screen Shot 2022-04-21 at 12 46 25 PM" src="https://user-images.githubusercontent.com/126065/164396507-34a41c08-02a2-48b2-ba4b-99f72a593d89.png">

**Comment by neverusedname** [comment] 2022-04-21 10:04
I am sorry, that was quite a long time ago, n I don't quite remember how we fixed it. Seems like we were tying to establish our own proxy servers and then later brought some exiting services.
Maybe you wanna try install proxy.py on a Linux machine or just try another proxy service, like mitmweb?



At 2022-04-21 10:08:13, "13096676951x" ***@***.***> wrote:

Hello, I have encountered this problem when I run the code, but my Python is version 3.6.11, can you tell me how you solve this problem? Very grateful for your help

**Comment by RoeweYaoo** [comment] 2022-04-22 09:35
> install proxy.py

**Comment by RoeweYaoo** [comment] 2022-04-22 09:36
> Hello, I have encountered this problem when I run the code, but my Python is version 3.6.11, can you tell me how you solve this problem? Very grateful for your help

hi, Can u solve it？？？I run a YOLOX train.py met it
