### ISSUE TITLE
[Cygwin] IS_WINDOWS returns False with `Windows 10`

### ISSUE THREAD

**Issue by cat-policlot** [abhinavsingh/proxy.py#1169] opened 2022-05-26 11:29 UTC
When I try to use proxy.py, it gives an error

Tested on:
cygwin python 3.9.10;
windows 10 home edition python 3.10.4

Error in the screenshots

![изображение](https://user-images.githubusercontent.com/44433191/170477448-fe0a8784-bca2-4d06-bd6d-99b335b12155.png)
![изображение](https://user-images.githubusercontent.com/44433191/170477804-3e7c29ee-fa9b-4920-96c4-bece37170e2c.png)

**Comment by abhinavsingh** [comment] 2022-05-26 13:18
Thank you for reporting this.

Under `_env_threadless_compliant` method we automatically disable multiprocessing based execution on windows.  But likely, this function is not picking up that it is running on windows when in cygwin environment.

Some rationale can be found here https://github.com/abhinavsingh/proxy.py#threads-vs-threadless .   Here is that function.  Can you check if this function returns True or False for your environment.  Likely, `IS_WINDOWS` constant is not True when running on `cygwin`.  Please help confirm

https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/common/constants.py#L25-L31

**Comment by cat-policlot** [comment] 2022-05-26 13:37
>>> IS_WINDOWS
False
>>>
>>>
>>>
>>> proxy.common.constants._env_threadless_compliant()
True
>>>
cygwin

**Comment by abhinavsingh** [comment] 2022-05-26 14:03
> cygwin

There you go, so looks like we need to get this fixed.  I'll push this out this week sometime and cut a new release.  Thank you for reporting this again.

**Comment by abhinavsingh** [comment] 2022-05-26 17:06
@cat-policlot WINERROR 10022 indicates an invalid argument was supplied.  This could happen for a variety of reasons, sometimes outside of `proxy.py` control.  E.g. this can happen if underlying socket was unable to bind to the port, but next we are trying to listen to it.  As far as I remember, there is no assertion check of whether bind succeeded.  We just proceed assuming it did worked.

One thing you could try is to run `proxy.py` from an administrative terminal.  I remember on Windows you could right click and open a shell as admin.  See if that helps.  Let me know.  Best

**Comment by abhinavsingh** [comment] 2022-06-15 18:28
@cat-policlot jFYI, `IS_WINDOWS` detection was fixed in #1196.  Can you give it a try when you get a chance.

Also were you able to figure out `WINERROR` problem.  Was it simply related to administrative terminal and/or how python/pip is setup locally?   Can you kindly confirm.

Today, I tried `proxy.py` on `Windows 11 + Python 3.9` combination.  And it seemed to work fine.  I routed entires windows traffic via proxy and I had a smooth experience.

I'll also give a try to `Windows 10 + Python 3.9` combination where you faced the `WINERROR`.  Though, I am unsure if I'll be able to reproduce it.  Let me know if you had any findings related to it.

Best

**Comment by abhinavsingh** [comment] 2022-08-13 07:16
@cat-policlot Closing this since `IS_WINDOWS` detection was fixed in #1196.  However, I haven't had a chance to try it out yet.  Someone with access to Cygwin must verify the fix.   Please reopen/contribute if there is bug in this detection.  Thank you

**Closed by abhinavsingh** 2022-08-13 07:16 UTC
Labels: Bug
