### ISSUE TITLE
Is it possible to modify https requests?

### ISSUE THREAD

**Issue by moham96** [abhinavsingh/proxy.py#126] opened 2019-10-11 11:24 UTC
**Is your feature request related to a problem? Please describe.**
I want to modify requests and response for https connections

**Describe the solution you'd like**
The solution would be to use a mechanism similar to debugging proxies like Fiddler and charles proxy, where the proxy server decodes the https response -> modify it -> re-sign it using a self generated SSL certificate. of course the client have to trust this certificate in his device/browser

**Comment by abhinavsingh** [comment] 2019-10-11 17:07
Are you looking for https://github.com/abhinavsingh/proxy.py#tls-interception?

**Comment by moham96** [comment] 2019-10-11 19:40
> Are you looking for https://github.com/abhinavsingh/proxy.py#tls-interception?
Yes,I tried those instructions, I can see that the response is re-signed by the self-generated certificate but I can't modify the request, I tried the  `plugin_examples.ModifyPostDataPlugin` with the tls-interception feature but the request is sent to the server unmodified.

**Comment by abhinavsingh** [comment] 2019-10-11 20:34
It works out of box for me.  What exactly did you try.

a) This is not a feature request, not a bug report, but a question
b) So please provide detailed steps and flags you used.

**Comment by abhinavsingh** [comment] 2019-10-11 20:36
Sorry about that, I am able to reproduce this now at my end 👍 , will take a look

**Comment by abhinavsingh** [comment] 2019-10-12 00:10
@moham96 Can you try the [x-forwarded-for](https://github.com/abhinavsingh/proxy.py/tree/x-forwarded-for) branch.  I have updated `ModifyPostDataPlugin` to handle cases when TLS interception is enabled.  Let me know if this works out for you.  Thanks for bringing this to my notice :)

Consider this API as temporary.  I am thinking of simply having one `handle_client_request` callback instead of `handle_pipeline_request` and `before_upstream_connection.

**Comment by moham96** [comment] 2019-10-12 10:16
> @moham96 Can you try the [x-forwarded-for](https://github.com/abhinavsingh/proxy.py/tree/x-forwarded-for) branch. I have updated `ModifyPostDataPlugin` to handle cases when TLS interception is enabled. Let me know if this works out for you. Thanks for bringing this to my notice :)
> 
> Consider this API as temporary. I am thinking of simply having one `handle_client_request` callback instead of `handle_pipeline_request` and `before_upstream_connection.

The branch works, thanks.
it seems like the APIs need a bit of work, it seems strange to modify the request in two places.

**Comment by abhinavsingh** [comment] 2019-10-12 15:01
Awesome.  Plugin APIs are in development phase, so yep we'll make
improvements.  Please check back once this branch is merged in develop,
I'll remove redundant callbacks.  :)

**Closed** 2019-10-13 00:43 UTC
Labels: Bug
