### ISSUE TITLE
Setting Public IP

### ISSUE THREAD

**Issue by Pezhvak** [abhinavsingh/proxy.py#38] opened 2019-02-05 14:25 UTC
how can i set my public ip? my server has thousands of ipv6. is it possible to choose one for each proxy?

**Comment by abhinavsingh** [comment] 2019-02-06 16:45
Duplicate of https://github.com/abhinavsingh/proxy.py/issues/36

**Closed by abhinavsingh** 2019-02-06 16:45 UTC
Labels: duplicate, question

**Comment by Pezhvak** [comment] 2019-02-06 19:30
sorry buy public ip i mean the outgoing ip, i have ipv4 which i want to listen on and use one of my ipv6s for outgoing traffic
