### ISSUE TITLE
Doesn't work on safari?

### ISSUE THREAD

**Issue by 5Zhiyong** [abhinavsingh/proxy.py#4] opened 2015-04-23 03:11 UTC
I tested through IE, curl, firefox. It works good. But on safari, it always get an error.

**Comment by abhinavsingh** [comment] 2018-10-17 09:48
<img width="825" alt="screen shot 2018-10-17 at 3 16 03 pm" src="https://user-images.githubusercontent.com/126065/47077900-a773bf80-d21f-11e8-86cc-91ede1ce4a51.png">

Unfortunately, unable to reproduce the same at my end. See above screenshot where I spent about 10-15 minutes browsing the internet _(Facebook, Google, YouTube, Twitter etc)_ with proxy.py enabled

What error did you get/see?

**Comment by abhinavsingh** [comment] 2018-12-10 09:47
Closing issue as I am unable to reproduce the same locally. Feel free to re-open with more details. Thank you.

**Closed by abhinavsingh** 2018-12-10 09:47 UTC
Labels: awaitingresponse
