### ISSUE TITLE
Not all logs are being written to the specified log file. 

### ISSUE THREAD

**Issue by hash3liZer** [abhinavsingh/proxy.py#596] opened 2021-08-28 15:21 UTC
I am trying to redirect all the logs from proxy.py to a specified file of mine using the flag: `--log-file`. However, the logs that are printed to the specified file are the first 4 messages which are these: 
```python
2021-08-27 22:00:24,218 - pid:64492 [I] load_plugins:337 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2021-08-27 22:00:24,218 - pid:64492 [I] load_plugins:337 - Loaded plugin __main__.Email
2021-08-27 22:00:24,258 - pid:64492 [I] listen:113 - Listening on 127.0.0.1:6491
2021-08-27 22:00:24,907 - pid:64492 [I] start_workers:136 - Started 4 workers
```

The rest of the logs are still being printed to the terminal. 

### Test on:
Windows 10 Pro, with Python 3.9

**Comment by abhinavsingh** [comment] 2021-09-15 17:00
@hash3liZer I think we do have an issue here.  Earlier I created a bug for it, see https://github.com/abhinavsingh/proxy.py/issues/473 (will mark this bug as a duplicate of the same).

This started happening after recent Python releases where they probably changed how `logger` behaves in a multiprocessing environment.

One clean way to obtain all logs will be, write a custom LogPlugin.  This plugin will simply print the log lines after the request ends.  Pipe the logs into a file or console.  Wdyt?

A proper fix will include routing logs via proxy.py inbuilt eventing framework.  So that all logs from multiple processes gets accumulated at a central place.  Unfortunately, I won't have time to get onto it anytime soon.

**Comment by abhinavsingh** [comment] 2021-09-15 17:00
Duplicate of #473

**Closed by abhinavsingh** 2021-09-15 17:00 UTC
Labels: Bug
