### ISSUE TITLE
Getting Full URL in SSL connections

### ISSUE THREAD

**Issue by puniaze** [abhinavsingh/proxy.py#83] opened 2019-09-23 10:10 UTC
I would like to know how can I get full URL of requested SSL resource?

Additionally, how can I change response content and response code with plugins?

I know there is plugin_examples.py but usage was unclear to me:

`raise proxy.HttpRequestRejected(status_code=418, body=b'I\'m a tea pot').`

**Comment by abhinavsingh** [comment] 2019-09-23 17:04
@puniaze Unfortunately `SSL` resource cannot be inspected or mutated.  What you are looking for is a `HTTPS` intercepting proxy, `proxy.py` doesn't support that currently.  `proxy.py` will add support for the same in future releases _(as also requested in #84)_

In general, such `HTTPS` interception tricks won't be possible in future due to `HSTS` and `HPKP`.  At-least all famous sites _(google.com, youtube.com, .....)_ seems to be using this now.  See https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning for some background.

**Comment by abhinavsingh** [comment] 2019-09-23 17:07
Marking it as duplicate of #84 , lets continue discussion there :)

**Closed by abhinavsingh** 2019-09-23 17:07 UTC
Labels: Duplicate, Enhancement

**Comment by puniaze** [comment] 2019-09-23 17:44
It is possible again today :)) The other tool I mentioned works smoothly :) Just take a look at it.

**Comment by abhinavsingh** [comment] 2019-09-23 17:51
> Additionally, how can I change response content and response code with plugins?

You might be able to work with `handle_upstream_response` which receives chunk of bytes received from upstream server.  You could then modify the chunk as necessary before returning to the client.  However, this will only work for HTTP requests (not HTTPS).
