### ISSUE TITLE
Error with simple curl command test

### ISSUE THREAD

**Issue by asieira** [abhinavsingh/proxy.py#60] opened 2019-08-10 16:41 UTC
Running IPv4 only server on Python 2.7.16 on Mac OS X (installed via homebrew) and trying to perform the following request:
```{bash}
$ export http_proxy=http://127.0.0.1:8899
$ curl -v checkip.amazonaws.com
* Uses proxy env variable http_proxy == 'http://127.0.0.1:8899'
*   Trying 127.0.0.1:8899...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8899 (#0)
> GET http://checkip.amazonaws.com/ HTTP/1.1
> Host: checkip.amazonaws.com
> User-Agent: curl/7.65.3
> Accept: */*
> Proxy-Connection: Keep-Alive
> 

```
It hangs. 

On the server side this is what I see:
```
$ python proxy.py --ipv4
2019-08-10 09:36:25,689 - INFO - pid:19824 - setup:730 - Starting 12 workers
2019-08-10 09:36:25,697 - INFO - pid:19824 - run:692 - Started server on port 8899
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
TypeError: expected string or Unicode object, NoneType found
```

**Comment by abhinavsingh** [comment] 2019-08-10 22:29
This is known issue only under develop branch, please upgrade to Python
3+.  Moving forward proxy.py will also stop supporting Python 2.7.

If you want to continue using Python 2.7, kindly utilize master branch or
simply pip install proxy.py

**Comment by abhinavsingh** [comment] 2019-08-11 08:28
Marking it as duplicate of https://github.com/abhinavsingh/proxy.py/issues/58

**Closed by abhinavsingh** 2019-08-11 08:28 UTC

**Comment by asieira** [comment] 2019-08-12 18:31
Thank you for the clarification! If only Python 3 will be supported, than I recommend two additional changes:

* remove Python 2 support tags from `setup.py`;
* add a runtime check to `sys.version_info` and error out if an incompatible version is being used.
