### ISSUE TITLE
ProxyPool can not handle https requests

### ISSUE THREAD

**Issue by JerryKwan** [abhinavsingh/proxy.py#568] opened 2021-06-20 02:04 UTC
**Check FAQs**
Please check [Frequently Asked Questions](https://github.com/abhinavsingh/proxy.py#frequently-asked-questions)
before opening a bug report.

**Describe the bug**
plugin/proxy_pool.py handle http requests gracefully, but when processing https request, exception occured

**To Reproduce**
1. proxy --port 9000 --log-level d
2. proxy --port 9001 --log-level d
3. proxy \
    --plugins proxy.plugin.ProxyPoolPlugin \
    --log-level d
4. curl -v -L -x http://127.0.0.1:8899 "https://httpbin.org/get"
5. errors are like this
*   Trying 127.0.0.1:8899...
* Connected to 127.0.0.1:8899 (127.0.0.1:8899) port 8899 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to httpbin.org:443
> CONNECT httpbin.org:443 HTTP/1.1
> Host: httpbin.org:443
> User-Agent: curl/7.77.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.0 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*  CAfile: none
*  CApath: none
* loaded libnssckbi.so
* CONNECT phase completed!
* CONNECT phase completed!
* NSS error -5938 (PR_END_OF_FILE_ERROR)
* Encountered end of file
* Closing connection 0
curl: (35) Encountered end of file

**Expected behavior**

**Version information**
 - OS: CentOS7.8
 - proxy.py Version [e.g. 1.1.1]

**Additional context**

**Screenshots**

**Comment by abhinavsingh** [comment] 2021-09-15 17:07
Thanks @JerryKwan for reporting this.  Unfortunately this is a known bug.  See https://github.com/abhinavsingh/proxy.py/issues/359

A proper fix will require re-haul of proxy.py core, where it must also allow plugins to register socket descriptors.  A sync plugin with async proxy.py core unfortunately doesn't work well :(

Marking this bug as a duplicate.

**Comment by abhinavsingh** [comment] 2021-09-15 17:07
Duplicate of https://github.com/abhinavsingh/proxy.py/issues/359

**Closed by abhinavsingh** 2021-09-15 17:07 UTC
Labels: Bug
