### ISSUE TITLE
Got stuck when sending POST with empty body

### ISSUE THREAD

**Issue by Torres9** [abhinavsingh/proxy.py#25] opened 2018-04-04 12:38 UTC
https://github.com/abhinavsingh/proxy.py/blob/ea33c0e2c9442a0f331f5171a1293a8aa1ccde95/proxy.py#L172

The parser part expects a GET request or a POST request with unempty body. Should change this line to make it work

**Comment by abhinavsingh** [comment] 2018-10-17 13:36
Can confirm this bug, marking this issue as a duplicate of https://github.com/abhinavsingh/proxy.py/issues/20

**Closed by abhinavsingh** 2018-10-17 13:36 UTC
Labels: bug
