### ISSUE TITLE
[ModifyChunkResponsePlugin] fails with "OSError when flushing buffer to client" with HTTPS PROXY

### ISSUE THREAD

**Issue by ar4development** [abhinavsingh/proxy.py#498] opened 2021-02-03 21:57 UTC
1. Run the proxy embedded:

```
import proxy
from proxy.plugin.modify_chunk_response import ModifyChunkResponsePlugin

if __name__ == '__main__':
    with proxy.start(
            ['--host', '127.0.0.1',
             '--port', '12233',
             '--log-level', 'DEBUG',
             '--ca-cert-file', '/YOUR_PATH_TO_CERT_FILES/myCA.pem',
             '--ca-key-file', '/YOUR_PATH_TO_CERT_FILES/myCA.key',
             '--ca-signing-key-file', '/YOUR_PATH_TO_CERT_FILES/myCA-signing.key'],
            plugins=
            [b'proxy.plugin.modify_chunk_response.ModifyChunkResponsePlugin',
             proxy.plugin.modify_chunk_response.ModifyChunkResponsePlugin]):
        import time
        time.sleep(10000)
```
2. When the main thread sleeps call the following `curl` command: `curl -v --proxy http://localhost:12233 --cacert /YOUR_PATH_TO_CERT_FILES/myCA.pem https://httpbin.org`

**Expected behavior**
Fake chunks from plugin are received by curl

**Observed behavior**

In curl:

```
*   Trying 127.0.0.1:12233...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 12233 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to httpbin.org:443
> CONNECT httpbin.org:443 HTTP/1.1
> Host: httpbin.org:443
> User-Agent: curl/7.68.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/alexey/Desktop/Dev/testing/CA/myCA.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=httpbin.org
*  start date: Jan 24 18:05:22 2021 GMT
*  expire date: Jan 24 18:05:22 2023 GMT
*  subjectAltName: host "httpbin.org" matched cert's "httpbin.org"
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=Test MITM python proxy
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection #0 to host localhost left intact
```
In proxy.py:

```
2021-02-04 00:41:25,552 - pid:284713 [D] initialize:104 - Handling connection <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12233), raddr=('127.0.0.1', 40592)>
2021-02-04 00:41:25,552 - pid:284713 [D] handle_readables:251 - Client is ready for reads, reading
2021-02-04 00:41:25,552 - pid:284713 [D] recv:63 - received 114 bytes from client
2021-02-04 00:41:25,552 - pid:284713 [D] connect_upstream:415 - Connecting to upstream httpbin.org:443
2021-02-04 00:41:25,673 - pid:284713 [D] connect_upstream:420 - Connected to upstream httpbin.org:443
2021-02-04 00:41:25,897 - pid:284713 [D] flush:92 - flushed 39 bytes to client
2021-02-04 00:41:25,900 - pid:284713 [D] wrap_client:560 - TLS interception using /home/alexey/.proxy/certificates/httpbin.org.pem
2021-02-04 00:41:25,900 - pid:284713 [D] handle_readables:300 - Updated client conn to <ssl.SSLSocket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12233), raddr=('127.0.0.1', 40592)>
2021-02-04 00:41:25,900 - pid:284713 [D] handle_readables:251 - Client is ready for reads, reading
2021-02-04 00:41:25,900 - pid:284713 [D] recv:63 - received 75 bytes from client
2021-02-04 00:41:25,901 - pid:284713 [D] write_to_descriptors:157 - Server is write ready, flushing buffer
2021-02-04 00:41:25,901 - pid:284713 [D] flush:92 - flushed 75 bytes to server
2021-02-04 00:41:26,014 - pid:284713 [D] read_from_descriptors:179 - Server is ready for reads, reading...
2021-02-04 00:41:26,014 - pid:284713 [D] recv:63 - received 239 bytes from server
2021-02-04 00:41:26,014 - pid:284713 [D] handle_writables:226 - Client is ready for writes, flushing buffer
2021-02-04 00:41:26,014 - pid:284713 [E] handle_writables:245 - OSError when flushing buffer to client
2021-02-04 00:41:26,014 - pid:284713 [D] shutdown:189 - Client connection closed
```

And the exception is:
```
Unable to display children:Error resolving variables Traceback (most recent call last):
  File "/proj/venv/lib/python3.8/site-packages/proxy/http/handler.py", line 239, in handle_writables
    self.client.flush()
  File "/proj/venv/lib/python3.8/site-packages/proxy/core/connection/connection.py", line 86, in flush
    sent: int = self.send(mv[:DEFAULT_MAX_SEND_SIZE])
  File "/proj/venv/lib/python3.8/site-packages/proxy/core/connection/connection.py", line 55, in send
    return self.connection.send(data)
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2472)
```

**Additional context**

The certificates seem fine since they work when I add headers to outgoing traffic and they also works if I just return the same chunk as receive in `handle_upstream_chunk` method

**Comment by abhinavsingh** [comment] 2021-02-09 05:32
@ar4development Apologies for missing this issue.  Unfortunately, currently `proxy.py` does not support TLS interception under `https` mode.

**Comment by ar4development** [comment] 2021-02-09 14:37
What do you mean? There is the dedicated section for this in [readme](https://github.com/abhinavsingh/proxy.py#tls-interception). Do you mean that does not work as intended?

**Comment by abhinavsingh** [comment] 2021-02-09 17:41
My apologies, I overlooked and thought your are running an https proxy.  Looks like you are not and TLS interception with http proxy should work out of box.

I am still confused where exactly are you facing issue.  You wrote::

`The certificates seem fine since they work when I add headers to outgoing traffic and they also works if I just return the same chunk as receive in handle_upstream_chunk method`

So are you trying to return a custom chunk?  Or are you using `ModifyChunkResponsePlugin` out-of-box hardcoded response?

**Comment by ar4development** [comment] 2021-02-10 12:13
No no. This time I'm trying to run the plugin out of the box. No modifications. Just what you have in your code base. I mentioned certificates to emphasize that they seem to be fine (I mean properly generated, etc. so that the certificates should not be the cause of the issue).

Basically I believe that running only those lines I provided should be enough to reproduce what I mean (of course with your own certs).

**Comment by ar4development** [comment] 2021-02-10 12:23
So conceptually the issue is:

- Start proxy with `ModifyChunkResponsePlugin` (just take the one from the examples) and TLS interception enabled
- Curl https://httpbin.org through that started proxy

EXPECTED: You see chunks which come from that plugin
OBSERVED: You see nothing but the mentioned error

**Comment by abhinavsingh** [comment] 2021-02-11 16:36
Thank you @ar4development for details, just wanted to update, I am traveling and will get back to it over the weekend.

**Comment by ar4development** [comment] 2021-02-19 10:28
Hi @abhinavsingh! Hope you enjoyed your traveling :) May we get back to the issue?

**Comment by abhinavsingh** [comment] 2021-02-19 16:35
Seems to work fine for me.

1. Started proxy.py with ModifyChunkResponsePlugin and TLS interception enabled
<img width="1174" alt="Screen Shot 2021-02-19 at 10 02 22 PM" src="https://user-images.githubusercontent.com/126065/108532838-4b913800-72fe-11eb-8f8c-6dbe0e29b094.png">

2. I was able to receive modified chunked response, see below
<img width="644" alt="Screen Shot 2021-02-19 at 10 02 47 PM" src="https://user-images.githubusercontent.com/126065/108532815-42a06680-72fe-11eb-8bb7-375d44e21015.png">

**Comment by ar4development** [comment] 2021-02-20 11:21
@abhinavsingh according to your screenshot you're connecting to HTTP, not HTTPs.

**Comment by abhinavsingh** [comment] 2021-02-21 10:49
@ar4development Correct.  This is what I referred to in https://github.com/abhinavsingh/proxy.py/issues/498#issuecomment-776115482 i.e. `proxy.py` doesn't support TLS interception when running in `https` mode, proxy must be started in `http` mode for TLS interception to work.

While this is technically possible, I haven't got to make this aspect of proxy.py work yet.  To work this around, you can use a TLS terminator server/proxy in front of proxy.py

**Comment by ar4development** [comment] 2021-02-22 20:43
I believe we understand the idea of MITM and TLS interception in different ways. you're accessing **http:**//httpbin.org/stream/5. Since the target resource is **http** not **https** you do not need any sort of TLS interception since the traffic is not encrypted. So why then you ever need to "enable" TLS interception if you eventually access HTTP resource where traffic is not TLS-encrypted?

**Comment by abhinavsingh** [comment] 2021-02-23 13:52
@ar4development apologies once again, our definition and understanding of TLS interception is the same.  I indeed accidentally used `http`.  Can confirm `https` request do result in `OSError when flushing buffer to client`.

This is most likely a side-effect of `return memoryview(b'')` placed at the end of `ModifyChunkResponsePlugin.handle_upstream_chunk` function.    To further debug, if you place a `print(chunk.tobytes())` at top of `ModifyChunkResponsePlugin.handle_upstream_chunk`, we can see chunk is received but response state is yet not `httpParserStates.COMPLETE`.   However, queueing an empty response results in OSError when TLS interception is on.

I'll need to revisit this again later at some point.  Thank you for reporting this and apologies for going in circles.

**Comment by abhinavsingh** [comment] 2021-11-06 16:52
@ar4development I think this got fixed in one of the recent updates to the core?  Because I am unable to reproduce this now.  Can you double check and verify please.  Thank you (see screenshots).

<img width="1089" alt="Screen Shot 2021-11-06 at 10 20 32 PM" src="https://user-images.githubusercontent.com/126065/140617457-a3277afa-5b9e-4060-9944-72657af58a6f.png">

<img width="513" alt="Screen Shot 2021-11-06 at 10 20 12 PM" src="https://user-images.githubusercontent.com/126065/140617462-c932c223-cce4-4f9f-b610-4240735e6e4c.png">

<img width="651" alt="Screen Shot 2021-11-06 at 10 21 15 PM" src="https://user-images.githubusercontent.com/126065/140617466-d11415ea-cfad-4c47-82eb-a538bce5ca98.png">

**Comment by abhinavsingh** [comment] 2021-11-06 17:05
<img width="637" alt="Screen Shot 2021-11-06 at 10 30 12 PM" src="https://user-images.githubusercontent.com/126065/140617716-5f13110c-e86e-461f-8f67-f7115c73b957.png">

@ar4development Please reopen if issue still persists at your end.

Please try https://github.com/abhinavsingh/proxy.py/pull/690 or wait for it to be merged before trying from `develop` branch.

Thank you

**Closed by abhinavsingh** 2021-11-06 17:05 UTC
Labels: Bug
